// FE/src/components/Main/IssuesList/Header.jsx
import styled from "styled-components";
import { Logo } from "../../../icons/logo";

export function Header() {
  return (
    <StyledHeader>
      <Logo />
      <img src="/img/frog.png" />
    </StyledHeader>
  );
}

const StyledHeader = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin: 25px 100px 50px 100px;
  img {
    width: 32px;
    height: 32px;
  }
`;

// frontend/src/components/common/Header.svelte
<header class="flex mb-[5rem] justify-between items-center">
    <div id="logo">
        <a class="text-4xl italic" href="/">Issue Tracker</a>
    </div>
    <a href="#">
        <img src="../../../../public/assets/profile_icon.svg" alt="User Profile Icon" class="user-profile-icon"/>
    </a>
</header>
