// FE/src/App.jsx
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import { Login } from "./components/Login/Login";
import { Main } from "./components/Main/Main";

function App() {
  return (
    <Router>
      <Routes>
        <Route path="/" element={<Login />} />
        <Route path="/login" element={<Login />} />
        <Route path="/issues" element={<Main />} />
      </Routes>
    </Router>
  );
}

export default App;

// frontend/src/App.svelte
<script>
  import Router from './route.svelte'
  import Header from "./components/common/Header.svelte";
  // import {Route} from "tinro";
  // import IssueAddPage from "./pages/issue/IssueAddPage.svelte";
  // import Header from "./components/common/Header.svelte";
  // import IssueDetailPage from "./pages/issue/IssueDetailPage.svelte";
  // import IssueListPage from "./pages/issue/IssueListPage.svelte";
</script>

<Header />
<div id="main-container">
  <Router />
</div>

<!--<Header />-->
<!--<div id="container">-->
<!--  <Route path="/">-->
<!--    <IssueListPage />-->
<!--  </Route>-->
<!--  <Route path="/issues">-->
<!--    <IssueListPage />-->
<!--  </Route>-->
<!--  <Route path="/issues/*" firstmatch>-->
<!--    <Route path="/add"><IssueAddPage/></Route>-->
<!--    <Route path="/:issueId"><IssueDetailPage/></Route>-->
<!--  </Route>-->
<!--</div>-->
