// frontend/src/components/common/Header.svelte
<header class="flex mb-[5rem] justify-between items-center">
    <div id="logo">
        <a class="text-4xl italic" href="/">Issue Tracker</a>
    </div>
    <a href="#">
        <img src="../../../../public/assets/profile_icon.svg" alt="User Profile Icon" class="user-profile-icon"/>
    </a>
</header>

// frontend/src/components/header/Header.tsx
import styled from "styled-components";
import pageLogo from "../../img/icon/pageLogo.svg";
import userIcon from "../../img/icon/userIcon.png";
import { useNavigate } from "react-router-dom";

function Header() {
  const navigate = useNavigate();

  return (
    <Wrapper>
      <HeaderLogo src={pageLogo} alt="page-logo" onClick={() => navigate("/")} />
      <HeaderUserIcon src={userIcon} />
    </Wrapper>
  );
}

const Wrapper = styled.div`
  width: 100%;
  height: 94px;
  display: flex;
  justify-content: space-between;
  align-items: center;
`;

const HeaderLogo = styled.img`
  width: 199px;
  height: 40px;
  cursor: pointer;
`;

const HeaderUserIcon = styled.img`
  width: 32px;
  height: 32px;
`;

export default Header;
